[2024-11-28T03:59:58.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T03:59:58.454+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:59:43.314041+00:00 [queued]>
[2024-11-28T03:59:58.462+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:59:43.314041+00:00 [queued]>
[2024-11-28T03:59:58.463+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T03:59:58.472+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 03:59:43.314041+00:00
[2024-11-28T03:59:58.477+0000] {standard_task_runner.py:72} INFO - Started process 77 to run task
[2024-11-28T03:59:58.480+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T03:59:43.314041+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpazkkj_d5']
[2024-11-28T03:59:58.481+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask load_bronze
[2024-11-28T03:59:58.521+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:59:43.314041+00:00 [running]> on host 120f6b2b8c94
[2024-11-28T03:59:58.588+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T03:59:43.314041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T03:59:43.314041+00:00'
[2024-11-28T03:59:58.589+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T03:59:58.599+0000] {load_bronze_module.py:109} INFO - Iniciando a tarefa load_bronze
[2024-11-28T03:59:58.599+0000] {load_bronze_module.py:185} ERROR - Erro ao salvar dados na camada Bronze: getenv() got an unexpected keyword argument 'default_var'
[2024-11-28T03:59:58.599+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 113, in load_bronze
    s3_bucket = os.getenv('S3_BUCKET', default_var=None)
TypeError: getenv() got an unexpected keyword argument 'default_var'
[2024-11-28T03:59:58.609+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T03:59:43.314041+00:00, execution_date=20241128T035943, start_date=20241128T035958, end_date=20241128T035958
[2024-11-28T03:59:58.621+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T03:59:58.622+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 121 for task load_bronze (getenv() got an unexpected keyword argument 'default_var'; 77)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 113, in load_bronze
    s3_bucket = os.getenv('S3_BUCKET', default_var=None)
TypeError: getenv() got an unexpected keyword argument 'default_var'
[2024-11-28T03:59:58.653+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T03:59:58.672+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T03:59:58.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
