[2024-11-28T02:51:15.709+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T02:51:15.721+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:50:45.463844+00:00 [queued]>
[2024-11-28T02:51:15.727+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:50:45.463844+00:00 [queued]>
[2024-11-28T02:51:15.727+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T02:51:15.736+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 02:50:45.463844+00:00
[2024-11-28T02:51:15.740+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-11-28T02:51:15.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T02:50:45.463844+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpe8dnj3lk']
[2024-11-28T02:51:15.744+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask load_bronze
[2024-11-28T02:51:15.779+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:50:45.463844+00:00 [running]> on host 61c850d9ce27
[2024-11-28T02:51:15.834+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T02:50:45.463844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T02:50:45.463844+00:00'
[2024-11-28T02:51:15.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T02:51:15.845+0000] {load_bronze_module.py:101} INFO - Iniciando a tarefa load_bronze
[2024-11-28T02:51:15.974+0000] {load_bronze_module.py:112} INFO - Recebidos 8355 registros para carregar na camada Bronze
[2024-11-28T02:51:18.328+0000] {load_bronze_module.py:62} INFO - Sessão Spark criada com sucesso
[2024-11-28T02:51:18.329+0000] {load_bronze_module.py:116} INFO - Sessão Spark criada com sucesso
[2024-11-28T02:51:18.330+0000] {load_bronze_module.py:136} INFO - Criando DataFrame com Spark
[2024-11-28T02:51:21.415+0000] {load_bronze_module.py:139} INFO - DataFrame criado com sucesso
[2024-11-28T02:51:21.416+0000] {load_bronze_module.py:141} INFO - Verificando dados que não atendem ao padrão
[2024-11-28T02:51:28.585+0000] {load_bronze_module.py:169} ERROR - Erro ao salvar dados na camada Bronze: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/***/scripts/load_bronze_module.py", line 74, in validate_longitude
    return False
TypeError: float() argument must be a string or a number, not 'NoneType'

[2024-11-28T02:51:28.761+0000] {load_bronze_module.py:174} INFO - Sessão Spark finalizada e tarefa load_bronze concluída
[2024-11-28T02:51:28.762+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 146, in load_bronze
    invalid_longitudes = df_spark.filter(~col("is_valid_longitude")).count()
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 1193, in count
    return int(self._jdf.count())
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 74, in validate_longitude
    return False
TypeError: float() argument must be a string or a number, not 'NoneType'

[2024-11-28T02:51:28.786+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T02:50:45.463844+00:00, execution_date=20241128T025045, start_date=20241128T025115, end_date=20241128T025128
[2024-11-28T02:51:28.808+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T02:51:28.809+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task load_bronze (
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 74, in validate_longitude
    return False
TypeError: float() argument must be a string or a number, not 'NoneType'
; 78)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 146, in load_bronze
    invalid_longitudes = df_spark.filter(~col("is_valid_longitude")).count()
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 1193, in count
    return int(self._jdf.count())
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 74, in validate_longitude
    return False
TypeError: float() argument must be a string or a number, not 'NoneType'

[2024-11-28T02:51:28.840+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T02:51:28.874+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T02:51:28.876+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
