[2024-11-27T04:10:07.582+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:10:07.592+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:10:07.592+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-27T04:10:07.606+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-26 00:00:00+00:00
[2024-11-27T04:10:07.614+0000] {standard_task_runner.py:57} INFO - Started process 263 to run task
[2024-11-27T04:10:07.617+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmp63wx0990']
[2024-11-27T04:10:07.619+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask load_bronze
[2024-11-27T04:10:07.666+0000] {task_command.py:415} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [running]> on host df4e9c023f45
[2024-11-27T04:10:07.751+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-11-27T04:10:07.908+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 78, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 42, in create_spark_session
    .config("spark.hadoop.fs.s3a.access.key", Variable.get("AWS_ACCESS_KEY_ID")) \
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2024-11-27T04:10:07.916+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, execution_date=20241126T000000, start_date=20241127T041007, end_date=20241127T041007
[2024-11-27T04:10:07.927+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task load_bronze ('Variable AWS_ACCESS_KEY_ID does not exist'; 263)
[2024-11-27T04:10:07.949+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-27T04:10:07.964+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:26:40.567+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:26:40.574+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:26:40.574+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-27T04:26:40.585+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-26 00:00:00+00:00
[2024-11-27T04:26:40.591+0000] {standard_task_runner.py:57} INFO - Started process 284 to run task
[2024-11-27T04:26:40.595+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpyz7um2bc']
[2024-11-27T04:26:40.597+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask load_bronze
[2024-11-27T04:26:40.640+0000] {task_command.py:415} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze scheduled__2024-11-26T00:00:00+00:00 [running]> on host c559e0f5374b
[2024-11-27T04:26:40.700+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-11-27T04:26:40.856+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 78, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 42, in create_spark_session
    .config("spark.hadoop.fs.s3a.access.key", Variable.get("AWS_ACCESS_KEY_ID")) \
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2024-11-27T04:26:40.862+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, execution_date=20241126T000000, start_date=20241127T042640, end_date=20241127T042640
[2024-11-27T04:26:40.870+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task load_bronze ('Variable AWS_ACCESS_KEY_ID does not exist'; 284)
[2024-11-27T04:26:40.888+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-27T04:26:40.902+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
