[2024-11-27T04:31:43.672+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [queued]>
[2024-11-27T04:31:43.681+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [queued]>
[2024-11-27T04:31:43.681+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-27T04:31:43.694+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-27 04:31:28.636933+00:00
[2024-11-27T04:31:43.700+0000] {standard_task_runner.py:57} INFO - Started process 401 to run task
[2024-11-27T04:31:43.703+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-27T04:31:28.636933+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpuhbdphd_']
[2024-11-27T04:31:43.706+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask load_bronze
[2024-11-27T04:31:43.756+0000] {task_command.py:415} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [running]> on host c559e0f5374b
[2024-11-27T04:31:43.845+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:31:28.636933+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:31:28.636933+00:00'
[2024-11-27T04:31:44.002+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 78, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 42, in create_spark_session
    .config("spark.hadoop.fs.s3a.access.key", Variable.get("AWS_ACCESS_KEY_ID")) \
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2024-11-27T04:31:44.009+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, execution_date=20241127T043128, start_date=20241127T043143, end_date=20241127T043144
[2024-11-27T04:31:44.019+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task load_bronze ('Variable AWS_ACCESS_KEY_ID does not exist'; 401)
[2024-11-27T04:31:44.036+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-27T04:31:44.053+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
